name: Create release on version change

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - id: check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
      - if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
      - if: steps.check.outputs.changed == 'true'
        run: npm ci
      - if: steps.check.outputs.changed == 'true'
        run: npm run test
      - if: steps.check.outputs.changed == 'true'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: steps.check.outputs.changed == 'true'
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: umbrelCLI v${{ steps.check.outputs.version }}
          tag_name: v${{ steps.check.outputs.version }}
          body: TODO
